name: app_frotas
description: "App Frotas"
publish_to: 'Vólus Instituição de Pagamentos' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  get_it: ^8.0.2
  go_router: ^14.6.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

